lista = [['Selecione un nivel'],
['Dpto. Arquitectura y Urbanismo'],
['Dpto. Ciencias Basicas Medicas'],
['Dpto. Comunicacion Social'],
['Dpto. Cs Politica y Rel Intern'],
['Dpto. Derecho'],
['Dpto. Dise?o'],
['Dpto. Educacion'],
['Dpto. Emprendim y Management'],
['Dpto. Enfermeria'],
['Dpto. Espa?ol'],
['Dpto. Finanzas y Contaduria'],
['Dpto. Fisica'],
['Dpto. Historia y Cs. Sociales'],
['Dpto. Humanidades y Filosofia'],
['Dpto. Ing. Civil y Ambiental'],
['Dpto. Ingenieria Basica'],
['Dpto. Ingenieria Industrial'],
['Dpto. Ingenieria Mecanica'],
['Dpto. Ingenieria de Sistemas'],
['Dpto. Lenguas'],
['Dpto. Lenguas Extranjeras'],
['Dpto. Matematicas y estadistic'],
['Dpto. Medicina'],
['Dpto. Mercadeo y Neg. Internac'],
['Dpto. Minors Ingenierias'],
['Dpto. Musica'],
['Dpto. Odontologia'],
['Dpto. Psicologia'],
['Dpto. Quimica y Biologia'],
['Dpto. Relaciones Internac.'],
['Dpto. Salud Publica'],
['Dpto. Tecnologia'],
['Dpto. de Economia'],
['Dpto.Finanzas y Organizaciones'],
['Dpto.Ing Electrica', 'Electronica'],
['Selecione un NRC']]

print(len(lista))